spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nursing?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  mail:
    host: smtp.naver.com
    port: 465
    username: yysskk9652@naver.com
    password: BPRPK3H6EU5D
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha